### ISSUE TITLE
problem with composer >= 2.0.9

### ISSUE THREAD

**Issue by michabbb** [Insolita/unused-scanner#36] opened 2021-03-07 21:52 UTC
hi there, 

my apologies in case I am totally wrong here.
i am using this package with version with "^1.3" inside my composer.json with PHP 5.6.9 as fixed PHP version. (yeah i know, super old).
i was wondering, why composer now takes minutes instead of seconds when just using composer with `-h` - so with nothing.
turned out, that this package uses `nesbot/carbon (>=1.22)` and this package requires `kylekatarnls/update-helper (^1.1)`.
and the helper is scanning all my files, while composer <= 2.0.8 is not.

i don´t know what really causes that behavior, but in case it has something to do with this package i wanted to let you know.

thanks !

https://github.com/composer/composer/issues/9760

**Comment by Insolita** [comment] 2021-03-07 22:21
Unfortunately, the problem still not clear to me. Which scanner config you use? Are you install scanner globally, with composer global require?  What is slow - composer work, or scanner work? 
Are you sure that you use this util and not a composer plugin https://github.com/composer-unused/composer-unused ?

**Comment by michabbb** [comment] 2021-03-07 22:24
the problem exists not because of this project, i am not even using this scanner. i just wanted to let you know, that your project uses a project that uses a project that behaves differently based on the composer version, that´s all. as said, if this don´t bother you, it´s absolutely fine, i just wanted to let you know where the plugin - in my special case - is coming from ;)

**Comment by Insolita** [comment] 2021-03-07 22:26
Ah, I understand, thanks

**Comment by michabbb** [comment] 2021-03-07 22:28
to be clear: your package IS installed in my project, but i didn´t use the scanner since a long time. but because this special plugin made me nuts... i was looking inside the dependency tree, where this plugin is coming from. and the result u see in my first posting ;)

**Comment by michabbb** [comment] 2021-03-07 22:51
it looks like the "update helper" is removed inside carbon since version [1.4.0](https://github.com/briannesbitt/Carbon/blob/1.4.0/composer.json).
in 1.39.1 it´s there.

**Comment by Seldaek** [comment] 2021-03-09 08:50
@michabbb IMO this should be reported to https://github.com/kylekatarnls/update-helper - as it seems to do something which misbehaves with Composer 2.0.9+. I have no idea what they are doing in that project but if the project author figures out the issue I'm happy to help out from the Composer side of things. Feel free to cc me on the issue if you create one.

@Insolita IMO this can be closed and I don't think you necessarily need to remove Carbon, but maybe you should allow carbon 2.x usage so at least people on modern PHP versions do not get stuck with this update helper dependency. I guess for @michabbb it wouldn't help if using PHP 5.6 is a requirement.

**Comment by Insolita** [comment] 2021-03-09 08:53
> @michabbb IMO this should be reported to https://github.com/kylekatarnls/update-helper - as it seems to do something which misbehaves with Composer 2.0.9+. I have no idea what they are doing in that project but if the project author figures out the issue I'm happy to help out from the Composer side of things. Feel free to cc me on the issue if you create one.
> 
> @Insolita IMO this can be closed and I don't think you necessarily need to remove Carbon, but maybe you should allow carbon 2.x usage so at least people on modern PHP versions do not get stuck with this update helper dependency. I guess for @michabbb it wouldn't help if using PHP 5.6 is a requirement.

Honestly, Carbon dependency is not so necessary, native Datetime will be enough

**Comment by Seldaek** [comment] 2021-03-09 08:57
Yeah if you can get rid of it that's fine too of course, but that won't fix the root cause in the update-helper project (which is installed a lot probably due to all Carbon 1.x users).

**Closed as completed** 2021-04-15 11:17 UTC
